package bean;
// Generated 13/10/2025 10:42:42 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * LbfMarcas generated by hbm2java
 */
@Entity
@Table(name="lbf_marcas"
    ,catalog="db_luana_santos"
)
public class lbf_Marcas  implements java.io.Serializable {


     private int lbfIdMarcas;
     private String lbfNomeDaMarca;
     private String lbfPaisDeOrigem;
     private String lbfTelefone;
     private String lbfEmail;
     private String lbfSite;
     private String lbfAtivo;
     private lbf_Produtos lbfProdutos;

    public lbf_Marcas() {
    }

	
    public lbf_Marcas(String lbfNomeDaMarca, String lbfAtivo) {
        this.lbfNomeDaMarca = lbfNomeDaMarca;
        this.lbfAtivo = lbfAtivo;
    }
    public lbf_Marcas(String lbfNomeDaMarca, String lbfPaisDeOrigem, String lbfTelefone, String lbfEmail, String lbfSite, String lbfAtivo, lbf_Produtos lbfProdutos) {
       this.lbfNomeDaMarca = lbfNomeDaMarca;
       this.lbfPaisDeOrigem = lbfPaisDeOrigem;
       this.lbfTelefone = lbfTelefone;
       this.lbfEmail = lbfEmail;
       this.lbfSite = lbfSite;
       this.lbfAtivo = lbfAtivo;
       this.lbfProdutos = lbfProdutos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lbf_id_marcas", unique=true, nullable=false)
    public int getLbfIdMarcas() {
        return this.lbfIdMarcas;
    }
    
    public void setLbfIdMarcas(int lbfIdMarcas) {
        this.lbfIdMarcas = lbfIdMarcas;
    }

    
    @Column(name="lbf_nomeDaMarca", nullable=false, length=100)
    public String getLbfNomeDaMarca() {
        return this.lbfNomeDaMarca;
    }
    
    public void setLbfNomeDaMarca(String lbfNomeDaMarca) {
        this.lbfNomeDaMarca = lbfNomeDaMarca;
    }

    
    @Column(name="lbf_paisDeOrigem", length=50)
    public String getLbfPaisDeOrigem() {
        return this.lbfPaisDeOrigem;
    }
    
    public void setLbfPaisDeOrigem(String lbfPaisDeOrigem) {
        this.lbfPaisDeOrigem = lbfPaisDeOrigem;
    }

    
    @Column(name="lbf_telefone", length=15)
    public String getLbfTelefone() {
        return this.lbfTelefone;
    }
    
    public void setLbfTelefone(String lbfTelefone) {
        this.lbfTelefone = lbfTelefone;
    }

    
    @Column(name="lbf_email", length=80)
    public String getLbfEmail() {
        return this.lbfEmail;
    }
    
    public void setLbfEmail(String lbfEmail) {
        this.lbfEmail = lbfEmail;
    }

    
    @Column(name="lbf_site", length=100)
    public String getLbfSite() {
        return this.lbfSite;
    }
    
    public void setLbfSite(String lbfSite) {
        this.lbfSite = lbfSite;
    }

    
    @Column(name="lbf_ativo", nullable=false, length=1)
    public String getLbfAtivo() {
        return this.lbfAtivo;
    }
    
    public void setLbfAtivo(String lbfAtivo) {
        this.lbfAtivo = lbfAtivo;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="lbfMarcas")
    public lbf_Produtos getLbfProdutos() {
        return this.lbfProdutos;
    }
    
    public void setLbfProdutos(lbf_Produtos lbfProdutos) {
        this.lbfProdutos = lbfProdutos;
    }




}


