package bean;
// Generated 13/10/2025 10:42:42 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * LbfVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="lbf_vendas_produtos"
    ,catalog="db_luana_santos"
)
public class lbf_VendasProdutos  implements java.io.Serializable {


     private int lbfIdVendasProdutos;
     private lbf_Produtos lbfProdutos;
     private lbf_Vendas lbfVendas;
     private int lbfIdVenda;
     private int lbfIdProduto;
     private int lbfQuantidade;
     private double lbfValorUnitario;

    public lbf_VendasProdutos() {
    }

    public lbf_VendasProdutos(lbf_Produtos lbfProdutos, lbf_Vendas lbfVendas, int lbfIdVenda, int lbfIdProduto, int lbfQuantidade, double lbfValorUnitario) {
       this.lbfProdutos = lbfProdutos;
       this.lbfVendas = lbfVendas;
       this.lbfIdVenda = lbfIdVenda;
       this.lbfIdProduto = lbfIdProduto;
       this.lbfQuantidade = lbfQuantidade;
       this.lbfValorUnitario = lbfValorUnitario;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="lbfProdutos"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="lbf_id_vendasProdutos", unique=true, nullable=false)
    public int getLbfIdVendasProdutos() {
        return this.lbfIdVendasProdutos;
    }
    
    public void setLbfIdVendasProdutos(int lbfIdVendasProdutos) {
        this.lbfIdVendasProdutos = lbfIdVendasProdutos;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public lbf_Produtos getLbfProdutos() {
        return this.lbfProdutos;
    }
    
    public void setLbfProdutos(lbf_Produtos lbfProdutos) {
        this.lbfProdutos = lbfProdutos;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public lbf_Vendas getLbfVendas() {
        return this.lbfVendas;
    }
    
    public void setLbfVendas(lbf_Vendas lbfVendas) {
        this.lbfVendas = lbfVendas;
    }

    
    @Column(name="lbf_id_venda", nullable=false)
    public int getLbfIdVenda() {
        return this.lbfIdVenda;
    }
    
    public void setLbfIdVenda(int lbfIdVenda) {
        this.lbfIdVenda = lbfIdVenda;
    }

    
    @Column(name="lbf_id_produto", nullable=false)
    public int getLbfIdProduto() {
        return this.lbfIdProduto;
    }
    
    public void setLbfIdProduto(int lbfIdProduto) {
        this.lbfIdProduto = lbfIdProduto;
    }

    
    @Column(name="lbf_quantidade", nullable=false)
    public int getLbfQuantidade() {
        return this.lbfQuantidade;
    }
    
    public void setLbfQuantidade(int lbfQuantidade) {
        this.lbfQuantidade = lbfQuantidade;
    }

    
    @Column(name="lbf_valor_unitario", nullable=false, precision=10)
    public double getLbfValorUnitario() {
        return this.lbfValorUnitario;
    }
    
    public void setLbfValorUnitario(double lbfValorUnitario) {
        this.lbfValorUnitario = lbfValorUnitario;
    }




}


