package bean;
// Generated 13/10/2025 10:42:42 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LbfClientes generated by hbm2java
 */
@Entity
@Table(name="lbf_clientes"
    ,catalog="db_luana_santos"
)
public class lbf_Clientes  implements java.io.Serializable {


     private int lbfIdClientes;
     private String lbfNome;
     private String lbfCpf;
     private String lbfRg;
     private String lbfSexo;
     private Date lbfDataDeNascimento;
     private String lbfCelular;
     private String lbfEmail;
     private String lbfCep;
     private String lbfEndereco;
     private String lbfBairro;
     private String lbfCidade;
     private String lbfEstado;
     private String lbfAtivo;
     private String lbfEstadoCivil;
     private lbf_Vendas lbfVendas;

    public lbf_Clientes() {
    }

	
    public lbf_Clientes(String lbfNome, String lbfCpf, String lbfSexo, Date lbfDataDeNascimento, String lbfCelular, String lbfAtivo, String lbfEstadoCivil) {
        this.lbfNome = lbfNome;
        this.lbfCpf = lbfCpf;
        this.lbfSexo = lbfSexo;
        this.lbfDataDeNascimento = lbfDataDeNascimento;
        this.lbfCelular = lbfCelular;
        this.lbfAtivo = lbfAtivo;
        this.lbfEstadoCivil = lbfEstadoCivil;
    }
    public lbf_Clientes(String lbfNome, String lbfCpf, String lbfRg, String lbfSexo, Date lbfDataDeNascimento, String lbfCelular, String lbfEmail, String lbfCep, String lbfEndereco, String lbfBairro, String lbfCidade, String lbfEstado, String lbfAtivo, String lbfEstadoCivil, lbf_Vendas lbfVendas) {
       this.lbfNome = lbfNome;
       this.lbfCpf = lbfCpf;
       this.lbfRg = lbfRg;
       this.lbfSexo = lbfSexo;
       this.lbfDataDeNascimento = lbfDataDeNascimento;
       this.lbfCelular = lbfCelular;
       this.lbfEmail = lbfEmail;
       this.lbfCep = lbfCep;
       this.lbfEndereco = lbfEndereco;
       this.lbfBairro = lbfBairro;
       this.lbfCidade = lbfCidade;
       this.lbfEstado = lbfEstado;
       this.lbfAtivo = lbfAtivo;
       this.lbfEstadoCivil = lbfEstadoCivil;
       this.lbfVendas = lbfVendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lbf_id_clientes", unique=true, nullable=false)
    public int getLbfIdClientes() {
        return this.lbfIdClientes;
    }
    
    public void setLbfIdClientes(int lbfIdClientes) {
        this.lbfIdClientes = lbfIdClientes;
    }

    
    @Column(name="lbf_nome", nullable=false, length=100)
    public String getLbfNome() {
        return this.lbfNome;
    }
    
    public void setLbfNome(String lbfNome) {
        this.lbfNome = lbfNome;
    }

    
    @Column(name="lbf_cpf", nullable=false, length=14)
    public String getLbfCpf() {
        return this.lbfCpf;
    }
    
    public void setLbfCpf(String lbfCpf) {
        this.lbfCpf = lbfCpf;
    }

    
    @Column(name="lbf_rg", length=12)
    public String getLbfRg() {
        return this.lbfRg;
    }
    
    public void setLbfRg(String lbfRg) {
        this.lbfRg = lbfRg;
    }

    
    @Column(name="lbf_sexo", nullable=false, length=10)
    public String getLbfSexo() {
        return this.lbfSexo;
    }
    
    public void setLbfSexo(String lbfSexo) {
        this.lbfSexo = lbfSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lbf_dataDeNascimento", nullable=false, length=10)
    public Date getLbfDataDeNascimento() {
        return this.lbfDataDeNascimento;
    }
    
    public void setLbfDataDeNascimento(Date lbfDataDeNascimento) {
        this.lbfDataDeNascimento = lbfDataDeNascimento;
    }

    
    @Column(name="lbf_celular", nullable=false, length=15)
    public String getLbfCelular() {
        return this.lbfCelular;
    }
    
    public void setLbfCelular(String lbfCelular) {
        this.lbfCelular = lbfCelular;
    }

    
    @Column(name="lbf_email", length=80)
    public String getLbfEmail() {
        return this.lbfEmail;
    }
    
    public void setLbfEmail(String lbfEmail) {
        this.lbfEmail = lbfEmail;
    }

    
    @Column(name="lbf_cep", length=9)
    public String getLbfCep() {
        return this.lbfCep;
    }
    
    public void setLbfCep(String lbfCep) {
        this.lbfCep = lbfCep;
    }

    
    @Column(name="lbf_endereco", length=100)
    public String getLbfEndereco() {
        return this.lbfEndereco;
    }
    
    public void setLbfEndereco(String lbfEndereco) {
        this.lbfEndereco = lbfEndereco;
    }

    
    @Column(name="lbf_bairro", length=50)
    public String getLbfBairro() {
        return this.lbfBairro;
    }
    
    public void setLbfBairro(String lbfBairro) {
        this.lbfBairro = lbfBairro;
    }

    
    @Column(name="lbf_cidade", length=50)
    public String getLbfCidade() {
        return this.lbfCidade;
    }
    
    public void setLbfCidade(String lbfCidade) {
        this.lbfCidade = lbfCidade;
    }

    
    @Column(name="lbf_estado", length=2)
    public String getLbfEstado() {
        return this.lbfEstado;
    }
    
    public void setLbfEstado(String lbfEstado) {
        this.lbfEstado = lbfEstado;
    }

    
    @Column(name="lbf_ativo", nullable=false, length=1)
    public String getLbfAtivo() {
        return this.lbfAtivo;
    }
    
    public void setLbfAtivo(String lbfAtivo) {
        this.lbfAtivo = lbfAtivo;
    }

    
    @Column(name="lbf_estado_civil", nullable=false, length=20)
    public String getLbfEstadoCivil() {
        return this.lbfEstadoCivil;
    }
    
    public void setLbfEstadoCivil(String lbfEstadoCivil) {
        this.lbfEstadoCivil = lbfEstadoCivil;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="lbf_Clientes")
    public lbf_Vendas getLbfVendas() {
        return this.lbfVendas;
    }
    
    public void setLbfVendas(lbf_Vendas lbfVendas) {
        this.lbfVendas = lbfVendas;
    }




}


