package bean;
// Generated 13/10/2025 10:42:42 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LbfFuncionarios generated by hbm2java
 */
@Entity
@Table(name="lbf_funcionarios"
    ,catalog="db_luana_santos"
)
public class lbf_Funcionarios  implements java.io.Serializable {


     private int lbfIdFuncionarios;
     private String lbfNome;
     private String lbfCpf;
     private String lbfCargo;
     private double lbfSalario;
     private Date lbfDataAdmissao;
     private String lbfAtivo;
     private lbf_Vendas lbfVendas;

    public lbf_Funcionarios() {
    }

	
    public lbf_Funcionarios(String lbfNome, String lbfCpf, String lbfCargo, double lbfSalario, Date lbfDataAdmissao, String lbfAtivo) {
        this.lbfNome = lbfNome;
        this.lbfCpf = lbfCpf;
        this.lbfCargo = lbfCargo;
        this.lbfSalario = lbfSalario;
        this.lbfDataAdmissao = lbfDataAdmissao;
        this.lbfAtivo = lbfAtivo;
    }
    public lbf_Funcionarios(String lbfNome, String lbfCpf, String lbfCargo, double lbfSalario, Date lbfDataAdmissao, String lbfAtivo, lbf_Vendas lbfVendas) {
       this.lbfNome = lbfNome;
       this.lbfCpf = lbfCpf;
       this.lbfCargo = lbfCargo;
       this.lbfSalario = lbfSalario;
       this.lbfDataAdmissao = lbfDataAdmissao;
       this.lbfAtivo = lbfAtivo;
       this.lbfVendas = lbfVendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lbf_id_funcionarios", unique=true, nullable=false)
    public int getLbfIdFuncionarios() {
        return this.lbfIdFuncionarios;
    }
    
    public void setLbfIdFuncionarios(int lbfIdFuncionarios) {
        this.lbfIdFuncionarios = lbfIdFuncionarios;
    }

    
    @Column(name="lbf_nome", nullable=false, length=100)
    public String getLbfNome() {
        return this.lbfNome;
    }
    
    public void setLbfNome(String lbfNome) {
        this.lbfNome = lbfNome;
    }

    
    @Column(name="lbf_cpf", nullable=false, length=14)
    public String getLbfCpf() {
        return this.lbfCpf;
    }
    
    public void setLbfCpf(String lbfCpf) {
        this.lbfCpf = lbfCpf;
    }

    
    @Column(name="lbf_cargo", nullable=false, length=50)
    public String getLbfCargo() {
        return this.lbfCargo;
    }
    
    public void setLbfCargo(String lbfCargo) {
        this.lbfCargo = lbfCargo;
    }

    
    @Column(name="lbf_salario", nullable=false, precision=10)
    public double getLbfSalario() {
        return this.lbfSalario;
    }
    
    public void setLbfSalario(double lbfSalario) {
        this.lbfSalario = lbfSalario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lbf_dataAdmissao", nullable=false, length=10)
    public Date getLbfDataAdmissao() {
        return this.lbfDataAdmissao;
    }
    
    public void setLbfDataAdmissao(Date lbfDataAdmissao) {
        this.lbfDataAdmissao = lbfDataAdmissao;
    }

    
    @Column(name="lbf_ativo", nullable=false, length=1)
    public String getLbfAtivo() {
        return this.lbfAtivo;
    }
    
    public void setLbfAtivo(String lbfAtivo) {
        this.lbfAtivo = lbfAtivo;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="lbfClientes")
    public lbf_Vendas getLbfVendas() {
        return this.lbfVendas;
    }
    
    public void setLbfVendas(lbf_Vendas lbfVendas) {
        this.lbfVendas = lbfVendas;
    }




}


