package bean;
// Generated 13/10/2025 10:42:42 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * LbfProdutos generated by hbm2java
 */
@Entity
@Table(name="lbf_produtos"
    ,catalog="db_luana_santos"
)
public class lbf_Produtos  implements java.io.Serializable {


     private int lbfIdProdutos;
     private lbf_Marcas lbfMarcas;
     private String lbfNomeDoProduto;
     private String lbfDescricao;
     private double lbfPreco;
     private Date lbfValidade;
     private String lbfTamanho;
     private String lbfCategoria;
     private lbf_VendasProdutos lbfVendasProdutos;

    public lbf_Produtos() {
    }

	
    public lbf_Produtos(lbf_Marcas lbfMarcas, String lbfNomeDoProduto, double lbfPreco, Date lbfValidade, String lbfTamanho, String lbfCategoria) {
        this.lbfMarcas = lbfMarcas;
        this.lbfNomeDoProduto = lbfNomeDoProduto;
        this.lbfPreco = lbfPreco;
        this.lbfValidade = lbfValidade;
        this.lbfTamanho = lbfTamanho;
        this.lbfCategoria = lbfCategoria;
    }
    public lbf_Produtos(lbf_Marcas lbfMarcas, String lbfNomeDoProduto, String lbfDescricao, double lbfPreco, Date lbfValidade, String lbfTamanho, String lbfCategoria, lbf_VendasProdutos lbfVendasProdutos) {
       this.lbfMarcas = lbfMarcas;
       this.lbfNomeDoProduto = lbfNomeDoProduto;
       this.lbfDescricao = lbfDescricao;
       this.lbfPreco = lbfPreco;
       this.lbfValidade = lbfValidade;
       this.lbfTamanho = lbfTamanho;
       this.lbfCategoria = lbfCategoria;
       this.lbfVendasProdutos = lbfVendasProdutos;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="lbfMarcas"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="lbf_id_produtos", unique=true, nullable=false)
    public int getLbfIdProdutos() {
        return this.lbfIdProdutos;
    }
    
    public void setLbfIdProdutos(int lbfIdProdutos) {
        this.lbfIdProdutos = lbfIdProdutos;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public lbf_Marcas getLbfMarcas() {
        return this.lbfMarcas;
    }
    
    public void setLbfMarcas(lbf_Marcas lbfMarcas) {
        this.lbfMarcas = lbfMarcas;
    }

    
    @Column(name="lbf_nomeDoProduto", nullable=false, length=100)
    public String getLbfNomeDoProduto() {
        return this.lbfNomeDoProduto;
    }
    
    public void setLbfNomeDoProduto(String lbfNomeDoProduto) {
        this.lbfNomeDoProduto = lbfNomeDoProduto;
    }

    
    @Column(name="lbf_descricao", length=200)
    public String getLbfDescricao() {
        return this.lbfDescricao;
    }
    
    public void setLbfDescricao(String lbfDescricao) {
        this.lbfDescricao = lbfDescricao;
    }

    
    @Column(name="lbf_preco", nullable=false, precision=10)
    public double getLbfPreco() {
        return this.lbfPreco;
    }
    
    public void setLbfPreco(double lbfPreco) {
        this.lbfPreco = lbfPreco;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lbf_validade", nullable=false, length=10)
    public Date getLbfValidade() {
        return this.lbfValidade;
    }
    
    public void setLbfValidade(Date lbfValidade) {
        this.lbfValidade = lbfValidade;
    }

    
    @Column(name="lbf_tamanho", nullable=false, length=20)
    public String getLbfTamanho() {
        return this.lbfTamanho;
    }
    
    public void setLbfTamanho(String lbfTamanho) {
        this.lbfTamanho = lbfTamanho;
    }

    
    @Column(name="lbf_categoria", nullable=false, length=50)
    public String getLbfCategoria() {
        return this.lbfCategoria;
    }
    
    public void setLbfCategoria(String lbfCategoria) {
        this.lbfCategoria = lbfCategoria;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="lbfProdutos")
    public lbf_VendasProdutos getLbfVendasProdutos() {
        return this.lbfVendasProdutos;
    }
    
    public void setLbfVendasProdutos(lbf_VendasProdutos lbfVendasProdutos) {
        this.lbfVendasProdutos = lbfVendasProdutos;
    }




}


