package bean;
// Generated 03/11/2025 14:27:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * LbfFuncionarios generated by hbm2java
 */
@Entity
@Table(name="lbf_funcionarios"
    ,catalog="db_luana_santos"
)
public class LbfFuncionarios  implements java.io.Serializable {


     private int lbfIdFuncionarios;
     private String lbfNome;
     private String lbfCpf;
     private String lbfCargo;
     private double lbfSalario;
     private String lbfAtivo;
     private String lbfTelefone;
     private String lbfEmail;
     private LbfVendas lbfVendas;

    public LbfFuncionarios() {
    }

	
    public LbfFuncionarios(String lbfNome, String lbfCpf, String lbfCargo, double lbfSalario, String lbfAtivo, String lbfTelefone, String lbfEmail) {
        this.lbfNome = lbfNome;
        this.lbfCpf = lbfCpf;
        this.lbfCargo = lbfCargo;
        this.lbfSalario = lbfSalario;
        this.lbfAtivo = lbfAtivo;
        this.lbfTelefone = lbfTelefone;
        this.lbfEmail = lbfEmail;
    }
    public LbfFuncionarios(String lbfNome, String lbfCpf, String lbfCargo, double lbfSalario, String lbfAtivo, String lbfTelefone, String lbfEmail, LbfVendas lbfVendas) {
       this.lbfNome = lbfNome;
       this.lbfCpf = lbfCpf;
       this.lbfCargo = lbfCargo;
       this.lbfSalario = lbfSalario;
       this.lbfAtivo = lbfAtivo;
       this.lbfTelefone = lbfTelefone;
       this.lbfEmail = lbfEmail;
       this.lbfVendas = lbfVendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lbf_id_funcionarios", unique=true, nullable=false)
    public int getLbfIdFuncionarios() {
        return this.lbfIdFuncionarios;
    }
    
    public void setLbfIdFuncionarios(int lbfIdFuncionarios) {
        this.lbfIdFuncionarios = lbfIdFuncionarios;
    }

    
    @Column(name="lbf_nome", nullable=false, length=100)
    public String getLbfNome() {
        return this.lbfNome;
    }
    
    public void setLbfNome(String lbfNome) {
        this.lbfNome = lbfNome;
    }

    
    @Column(name="lbf_cpf", nullable=false, length=14)
    public String getLbfCpf() {
        return this.lbfCpf;
    }
    
    public void setLbfCpf(String lbfCpf) {
        this.lbfCpf = lbfCpf;
    }

    
    @Column(name="lbf_cargo", nullable=false, length=50)
    public String getLbfCargo() {
        return this.lbfCargo;
    }
    
    public void setLbfCargo(String lbfCargo) {
        this.lbfCargo = lbfCargo;
    }

    
    @Column(name="lbf_salario", nullable=false, precision=10)
    public double getLbfSalario() {
        return this.lbfSalario;
    }
    
    public void setLbfSalario(double lbfSalario) {
        this.lbfSalario = lbfSalario;
    }

    
    @Column(name="lbf_ativo", nullable=false, length=1)
    public String getLbfAtivo() {
        return this.lbfAtivo;
    }
    
    public void setLbfAtivo(String lbfAtivo) {
        this.lbfAtivo = lbfAtivo;
    }

    
    @Column(name="lbf_telefone", nullable=false, length=15)
    public String getLbfTelefone() {
        return this.lbfTelefone;
    }
    
    public void setLbfTelefone(String lbfTelefone) {
        this.lbfTelefone = lbfTelefone;
    }

    
    @Column(name="lbf_email", nullable=false, length=80)
    public String getLbfEmail() {
        return this.lbfEmail;
    }
    
    public void setLbfEmail(String lbfEmail) {
        this.lbfEmail = lbfEmail;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="lbfClientes")
    public LbfVendas getLbfVendas() {
        return this.lbfVendas;
    }
    
    public void setLbfVendas(LbfVendas lbfVendas) {
        this.lbfVendas = lbfVendas;
    }




}


