package bean;
// Generated 03/11/2025 14:27:43 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LbfUsuarios generated by hbm2java
 */
@Entity
@Table(name="lbf_usuarios"
    ,catalog="db_luana_santos"
)
public class LbfUsuarios  implements java.io.Serializable {


     private int lbfIdUsuarios;
     private String lbfNome;
     private String lbfApelido;
     private String lbfCpf;
     private String lbfSenha;
     private Date lbfDataNascimento;
     private String lbfNivel;
     private String lbfAtivo;

    public LbfUsuarios() {
    }

    public LbfUsuarios(String lbfNome, String lbfApelido, String lbfCpf, String lbfSenha, Date lbfDataNascimento, String lbfNivel, String lbfAtivo) {
       this.lbfNome = lbfNome;
       this.lbfApelido = lbfApelido;
       this.lbfCpf = lbfCpf;
       this.lbfSenha = lbfSenha;
       this.lbfDataNascimento = lbfDataNascimento;
       this.lbfNivel = lbfNivel;
       this.lbfAtivo = lbfAtivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lbf_id_usuarios", unique=true, nullable=false)
    public int getLbfIdUsuarios() {
        return this.lbfIdUsuarios;
    }
    
    public void setLbfIdUsuarios(int lbfIdUsuarios) {
        this.lbfIdUsuarios = lbfIdUsuarios;
    }

    
    @Column(name="lbf_nome", length=100)
    public String getLbfNome() {
        return this.lbfNome;
    }
    
    public void setLbfNome(String lbfNome) {
        this.lbfNome = lbfNome;
    }

    
    @Column(name="lbf_apelido", length=50)
    public String getLbfApelido() {
        return this.lbfApelido;
    }
    
    public void setLbfApelido(String lbfApelido) {
        this.lbfApelido = lbfApelido;
    }

    
    @Column(name="lbf_cpf", length=14)
    public String getLbfCpf() {
        return this.lbfCpf;
    }
    
    public void setLbfCpf(String lbfCpf) {
        this.lbfCpf = lbfCpf;
    }

    
    @Column(name="lbf_senha")
    public String getLbfSenha() {
        return this.lbfSenha;
    }
    
    public void setLbfSenha(String lbfSenha) {
        this.lbfSenha = lbfSenha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lbf_dataNascimento", length=10)
    public Date getLbfDataNascimento() {
        return this.lbfDataNascimento;
    }
    
    public void setLbfDataNascimento(Date lbfDataNascimento) {
        this.lbfDataNascimento = lbfDataNascimento;
    }

    
    @Column(name="lbf_nivel", length=50)
    public String getLbfNivel() {
        return this.lbfNivel;
    }
    
    public void setLbfNivel(String lbfNivel) {
        this.lbfNivel = lbfNivel;
    }

    
    @Column(name="lbf_ativo", length=1)
    public String getLbfAtivo() {
        return this.lbfAtivo;
    }
    
    public void setLbfAtivo(String lbfAtivo) {
        this.lbfAtivo = lbfAtivo;
    }




}


