package bean;
// Generated 13/10/2025 10:42:42 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * LbfVendas generated by hbm2java
 */
@Entity
@Table(name="lbf_vendas"
    ,catalog="db_luana_santos"
)
public class LbfVendas  implements java.io.Serializable {


     private int lbfIdVendas;
     private LbfClientes lbfClientes;
     private LbfFuncionarios lbfFuncionarios;
     private Date lbfDataVenda;
     private int lbfIdClienteLbf;
     private int lbfIdFuncionarioLbf;
     private double lbfTotal;
     private LbfVendasProdutos lbfVendasProdutos;

    public LbfVendas() {
    }

	
    public LbfVendas(LbfClientes lbfClientes, LbfFuncionarios lbfFuncionarios, Date lbfDataVenda, int lbfIdClienteLbf, int lbfIdFuncionarioLbf, double lbfTotal) {
        this.lbfClientes = lbfClientes;
        this.lbfFuncionarios = lbfFuncionarios;
        this.lbfDataVenda = lbfDataVenda;
        this.lbfIdClienteLbf = lbfIdClienteLbf;
        this.lbfIdFuncionarioLbf = lbfIdFuncionarioLbf;
        this.lbfTotal = lbfTotal;
    }
    public LbfVendas(LbfClientes lbfClientes, LbfFuncionarios lbfFuncionarios, Date lbfDataVenda, int lbfIdClienteLbf, int lbfIdFuncionarioLbf, double lbfTotal, LbfVendasProdutos lbfVendasProdutos) {
       this.lbfClientes = lbfClientes;
       this.lbfFuncionarios = lbfFuncionarios;
       this.lbfDataVenda = lbfDataVenda;
       this.lbfIdClienteLbf = lbfIdClienteLbf;
       this.lbfIdFuncionarioLbf = lbfIdFuncionarioLbf;
       this.lbfTotal = lbfTotal;
       this.lbfVendasProdutos = lbfVendasProdutos;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="lbfClientes"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="lbf_id_vendas", unique=true, nullable=false)
    public int getLbfIdVendas() {
        return this.lbfIdVendas;
    }
    
    public void setLbfIdVendas(int lbfIdVendas) {
        this.lbfIdVendas = lbfIdVendas;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public LbfClientes getLbfClientes() {
        return this.lbfClientes;
    }
    
    public void setLbfClientes(LbfClientes lbfClientes) {
        this.lbfClientes = lbfClientes;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public LbfFuncionarios getLbfFuncionarios() {
        return this.lbfFuncionarios;
    }
    
    public void setLbfFuncionarios(LbfFuncionarios lbfFuncionarios) {
        this.lbfFuncionarios = lbfFuncionarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lbf_dataVenda", nullable=false, length=10)
    public Date getLbfDataVenda() {
        return this.lbfDataVenda;
    }
    
    public void setLbfDataVenda(Date lbfDataVenda) {
        this.lbfDataVenda = lbfDataVenda;
    }

    
    @Column(name="lbf_id_cliente_lbf", nullable=false)
    public int getLbfIdClienteLbf() {
        return this.lbfIdClienteLbf;
    }
    
    public void setLbfIdClienteLbf(int lbfIdClienteLbf) {
        this.lbfIdClienteLbf = lbfIdClienteLbf;
    }

    
    @Column(name="lbf_id_funcionario_lbf", nullable=false)
    public int getLbfIdFuncionarioLbf() {
        return this.lbfIdFuncionarioLbf;
    }
    
    public void setLbfIdFuncionarioLbf(int lbfIdFuncionarioLbf) {
        this.lbfIdFuncionarioLbf = lbfIdFuncionarioLbf;
    }

    
    @Column(name="lbf_total", nullable=false, precision=10)
    public double getLbfTotal() {
        return this.lbfTotal;
    }
    
    public void setLbfTotal(double lbfTotal) {
        this.lbfTotal = lbfTotal;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="lbfProdutos")
    public LbfVendasProdutos getLbfVendasProdutos() {
        return this.lbfVendasProdutos;
    }
    
    public void setLbfVendasProdutos(LbfVendasProdutos lbfVendasProdutos) {
        this.lbfVendasProdutos = lbfVendasProdutos;
    }




}


